# Generated by Django 6.1.2 on 2026-10-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('name', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('first_publish_date', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.work')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(through='books.WorkAuthor', to='books.author'),
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('work', 'author'), name='unique_work_author'),
        ),
    ]
